# Import libraries

In [ ]:
import numpy as np

# Note the impoertance of NumPy data arrays

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print("Array x is of shape: ", np.shape(x))
print("The array x contains the following elements:\n", format(x))

Array x is of shape:  (3, 3)
The array x contains the following elements:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# So-called 'Sparse Arrays' are important in ML:

In [ ]:
#scipi is a collection of functions for scientific computing
from scipy import sparse
#Create a 2D array - the identity matrix - with the leading diagonal as ones and ll else as 0s
#eye':  Identity matrix
eye = np.eye(4)
print("Here is an Identity matrix: \n", eye)
#Now convert to CSR (compressed sparse row)
#Only the nonzero entries are stored
sparse_matrix=sparse.csr_matrix(eye)
print("ScPy sparse matrix: \n", (sparse_matrix))


Here is an Identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ScPy sparse matrix: 
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


#Creating the same sparse matrix using COO (COOrdinate) format
Also known as the ijv or triplet format

---



---



In [ ]:
import numpy as np
data=np.ones(4)
row_indices=np.arange(4)
col_indices=np.arange(4)
eye_coo=sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n", eye_coo)

COO representation:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
